<?php

namespace App\Http\Resources\Hospital;

use Illuminate\Http\Resources\Json\JsonResource;

class MainRecourse extends JsonResource
{
    public function with($request)
    {
        return ; // TODO: Change the autogenerated stub
    }
}
